require('dotenv').config();

module.exports = {
    BASE_URL: process.env.BASE_URL,
    API_DOC_BASE_URL: process.env.API_DOC_BASE_URL,

    DATABASE_URL: process.env.DATABASE_URL,
    DATABASE_USERNAME: process.env.DATABASE_USERNAME,
    DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
    DATABASE_NAME: process.env.DATABASE_NAME,
    JOB_DATABASE_NAME: process.env.JOB_DATABASE_NAME,


    ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
    FCM_TOKEN_SECRET: process.env.FCM_TOKEN_SECRET,
    PROFILE_PIC_MEDIA_ENCRYPTION: process.env.PROFILE_PIC_MEDIA_ENCRYPTION,

    MEDIA_ROOT_PATH: process.env.MEDIA_ROOT_PATH,
    MEDIA_BASE_URL: process.env.MEDIA_BASE_URL,
    S3_BUCKET_NAME: process.env.S3_BUCKET_NAME,
    PROFILE_BASE_URL: process.env.PROFILE_BASE_URL,

    S3_BUCKET_REGION: process.env.S3_BUCKET_REGION,
    S3_BUCKET_ACCESS_KEY: process.env.S3_BUCKET_ACCESS_KEY,
    S3_BUCKET_SECRET_KEY: process.env.S3_BUCKET_SECRET_KEY,

    OAUTH_GOOGLE_WEB_CLIENT_ID: process.env.OAUTH_GOOGLE_WEB_CLIENT_ID,
    OAUTH_GOOGLE_ANDROID_CLIENT_ID: process.env.OAUTH_GOOGLE_ANDROID_CLIENT_ID,

    SMTP_HOST:process.env.SMTP_HOST,
    SMTP_USER:process.env.SMTP_USER,
    SMTP_PASSWORD:process.env.SMTP_PASSWORD,

    APP_NAME: process.env.APP_NAME
};